version: '3.8'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres
    environment:
      - DB_NAME=application_tracking_system
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=my-postgres
      - DB_PORT=5432

  my-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: application_tracking_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
